function H=getstart(par)

if isstruct(par)
    par = ['../data/' ...
           par.text ...
           '-' num2str(par.n) ...
           '-' num2str(par.fd) ...
           '-ep' num2str(par.ep) ...
           '-o' num2str(par.order) ...
           '-gc' num2str(par.gamma_c) ...
           '/H'];
    disp(['load "' par '"'])
end

H = loaddata(par);
