function H=getsol(par, dt, postfix)

if nargin < 3
  postfix = '';
end

if isstruct(par)
    par = ['../resdata/' ...
           par.test postfix ...
           '-' num2str(par.n) ...
           '-' num2str(par.fd) ...
           '-ep' num2str(par.ep) ...
           '-o' num2str(par.order) ...
           '-gc' num2str(par.gamma_c) ...
           '-dt' num2str(dt) ...
           '/result.txt'];
    disp(['load "' par '"'])
end

H = loaddata(par);
