function saveplot(par, dt, postfix)

if nargin < 3
  postfix = '';
end

H = getsol(par, dt, postfix);
f=figure('Visible','off');
set(gca, 'LooseInset', get(gca, 'TightInset'));
set(gcf, 'PaperUnits','inches', 'PaperPosition',[0 0 6 3])
set(gcf, 'PaperSize', [6 3]);

mt_plot(par, H);

filename = [ ...
    '../resdata/' ...
    par.test postfix ...
    '-' num2str(par.n) ...
    '-' num2str(par.fd) ...
    '-ep' num2str(par.ep) ...
    '-o' num2str(par.order) ...
    '-gc' num2str(par.gamma_c) ...
    '-dt' num2str(dt) ...
    ];

print('-dpdf','-r300', '-painters', [filename '.pdf']);
print('-dpng','-r300', '-painters', [filename '.png']);
